# Generated by Django 5.0 on 2023-12-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("restaurant", "0001_initial"),
        ("restaurant", "0002_add_xxx_field"),
        ("restaurant", "0003_xremove_yadd"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("websit", models.URLField(default="")),
                ("date_opened", models.DateField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("yyy", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
