# Generated by Django 5.0 on 2023-12-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]
    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="xxx",
            field=models.BooleanField(default=False),
        ),
    ]
