# Generated by Django 5.0 on 2023-12-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("restaurant", "0002_add_xxx_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="xxx",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="yyy",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
