# Generated by Django 5.0 on 2023-12-28 13:19
from django.db import migrations


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Restaurant = apps.get_model("restaurant", "Restaurant")
    for restaurant in Restaurant.objects.all():
        restaurant.name = f"{restaurant.name} restaurant"
        restaurant.save()


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_xremove_yadd"),
    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
