# Generated by Django 5.0 on 2023-12-28 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_auto_20231228_1319"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="websit",
            new_name="website",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="yyy",
        ),
    ]
