# Generated by Django 5.0 on 2023-12-29 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "restaurant",
            "0009_sale_alter_rating_options_alter_restaurant_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="updated_at",
        ),
    ]
