# Generated by Django 5.0 on 2023-12-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0010_remove_restaurant_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="restaurant_type",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="restaurant_type",
            field=models.CharField(
                choices=[("PR", "Persian"), ("IT", "Italian"), ("CH", "Chinese")],
                default="PR",
                max_length=2,
            ),
        ),
    ]
