# Generated by Django 5.0 on 2023-12-29 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0011_remove_rating_restaurant_type_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="rating",
            table_comment="This table stores user ratings for restaurants",
        ),
        migrations.AddField(
            model_name="sale",
            name="income",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="date_opened",
            field=models.DateField(db_comment="Date when the restaurant was opened"),
        ),
        migrations.AlterField(
            model_name="sale",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="restaurant.restaurant",
            ),
        ),
    ]
